### ISSUE TITLE
Error on register

### ISSUE THREAD

**Issue by thegergo02** [ZerataX/matrix-registration#70] opened 2021-07-23 06:55 UTC
### Describe the bug
When I send the register post request Python spits out this error:

```
[2021-07-23 08:46:50,750] ERROR in app: Exception on /register [POST]
Traceback (most recent call last):
  File "/etc/matrix-registration/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/etc/matrix-registration/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/etc/matrix-registration/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/etc/matrix-registration/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/etc/matrix-registration/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/etc/matrix-registration/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/etc/matrix-registration/lib/python3.9/site-packages/matrix_registration/api.py", line 169, in register
    if form.validate():
  File "/etc/matrix-registration/lib/python3.9/site-packages/wtforms/form.py", line 318, in validate
    return super(Form, self).validate(extra)
  File "/etc/matrix-registration/lib/python3.9/site-packages/wtforms/form.py", line 150, in validate
    if not field.validate(self, extra):
  File "/etc/matrix-registration/lib/python3.9/site-packages/wtforms/fields/core.py", line 226, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/etc/matrix-registration/lib/python3.9/site-packages/wtforms/fields/core.py", line 246, in _run_validation_chain
    validator(form, self)
  File "/etc/matrix-registration/lib/python3.9/site-packages/matrix_registration/api.py", line 82, in validate_username
    re.escape(domain) + \
  File "/usr/lib/python3.9/re.py", line 277, in escape
    pattern = str(pattern, 'latin1')
TypeError: decoding to str: need a bytes-like object, NoneType found
matrix_registration.app - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "/etc/matrix-registration/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/etc/matrix-registration/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/etc/matrix-registration/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/etc/matrix-registration/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/etc/matrix-registration/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/etc/matrix-registration/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/etc/matrix-registration/lib/python3.9/site-packages/matrix_registration/api.py", line 169, in register
    if form.validate():
  File "/etc/matrix-registration/lib/python3.9/site-packages/wtforms/form.py", line 318, in validate
    return super(Form, self).validate(extra)
  File "/etc/matrix-registration/lib/python3.9/site-packages/wtforms/form.py", line 150, in validate
    if not field.validate(self, extra):
  File "/etc/matrix-registration/lib/python3.9/site-packages/wtforms/fields/core.py", line 226, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/etc/matrix-registration/lib/python3.9/site-packages/wtforms/fields/core.py", line 246, in _run_validation_chain
    validator(form, self)
  File "/etc/matrix-registration/lib/python3.9/site-packages/matrix_registration/api.py", line 82, in validate_username
    re.escape(domain) + \
  File "/usr/lib/python3.9/re.py", line 277, in escape
    pattern = str(pattern, 'latin1')
TypeError: decoding to str: need a bytes-like object, NoneType found
```

###  To reproduce
Try to register.

### Expected behaviour
No errors.

### System
OS: Arch Linux ARM  
python version: 3.9.6  
matrix registration version: freshly installed from pip

**Comment by ZerataX** [comment] 2021-07-23 12:48
hmm can't reproduce this but seems like something went wrong trying to validate the username?
what user did you try to register and what did you set `server_name` to in the config?

**Comment by xelantro** [comment] 2021-07-25 21:37
I think it's a duplicate of what just got posted this monday in the matrix channel:
The issue is that your domain in server_location is invalid should look like this: `server_location: https//localhost:8008`

**Comment by thegergo02** [comment] 2021-08-01 17:42
Sorry for the late reply, this fix worked.

**Closed** 2021-08-01 17:42 UTC
